In [87]:
import numpy as np

In [88]:

X=np.empty(5)
FILE=open('data.csv','r')
temp=FILE.read().split('\n')
offset=0
for x in range(5):
    X[(x)]=temp[x+offset].split(',')[2]

In [89]:
class NeuralNet:
    def __init__(self):
        self.inputlayersize=5
        self.hiddenlayersize=6
        self.outputlayersize=1

        self.W1=np.random.randn(self.inputlayersize,\
            self.hiddenlayersize)

        self.W2=np.random.randn(self.hiddenlayersize,\
            self.outputlayersize)
    
    def Forward(self,X):
        self.z2=np.dot(X,self.W1)
        self.a2=self.ActivationFunction(self.z2)
        self.z3=np.dot(self.a2,self.W2)
        Yhat=self.ActivationFunction(self.z3)
        return Yhat
        
    def ActivationFunction(self,v):
        return np.tanh(v)

In [90]:
NN=NeuralNet()


In [91]:

Y=np.array([-1])

In [92]:
yHat=NN.Forward(X)

In [93]:

print(NN.W1)


[[ 0.09543053  0.43975    -0.22959595 -1.94634955 -1.03014614  1.64028162]
 [ 1.37910856  0.88388636 -2.29851868 -0.28014291  0.49724252  0.79163857]
 [ 0.2957169  -1.53685591 -1.06976089  0.00429429  0.35897304  0.22905428]
 [ 1.38997719 -1.56408778  0.50827197  1.18960173 -0.32269514  1.36626671]
 [-0.04544396  2.01790033  0.09211115 -1.74033543  1.03361065  1.70539253]]
